# The big picture

## 1. What is needed to build a decision tree (CART):
                
   **The principle of abstraction**

1. Question --> A node is splitted based on the question asked.
2. Split the data --> Based on the answer to the question, the data can be splitted into two new sets of data.
3. metric --> Used to measure the homogeinity of a node, such as gini impurity or entropy.
4. info_gain --> The change of the gini impurity or entropy before and after the split.(we need to maximize it to get the best node split)
5. get_best_split --> Based on the info_gain of all possible split, we will pick the question that gives use the best split. 
6. Leaf --> The end node (where no more info gained). It should contain the predictions we want.
7. Node --> a question can be asked to further lower and info gain and split into more nodes or leaves.


![Decision_Tree](img/decision_tree.png)

## 2. How are we going to structure our code:

1. Package our decision tree classifier into a class, and the class should be able to do the following:

    * train the model with training datasets.
    * predict the result with the trained model and new data.
    * some private methods to help build the class.
    * simple print method to visualize the tree.


2. How to represent the whole tree?

    * The tree (model) is made of nodes and leaves. So we will construct node and leaf classes and use them to represent the tree (model).

**Based on step 1, we can come up with the following structure:**

Note: 
1. X is matrix (features for multiple samples) 
2. x is vector (feature for a single sample)
3. y is vector (labels for all samples).

In [1]:
import numpy as np

In [2]:
class Question:
    """
    A node is splitted based on the question asked.
    """
    def __init__(self, column_number, feature):
        self.column_number = column_number
        self.feature = feature
    
    def __str__(self):
        """
        Some way to represent a question.
        """
        pass
    
    def ask(self, row):
        """
        Return:
            bool
        """  
        pass
    
    
class Leaf:
    """
    The end node (where no more info is gained). It should contain the predictions we want with only one type of label.
    """
    def __init__(self, y):
        self.prediction = self.y[0]
        
    def __str__(self):
        """
        Some way to represent a leaf.
        """
        pass
    
    @staticmethod
    def _label_counts(y):
        """
        Counts the number of the samples that have the same label.
        Return:
            counts: dict
        """
        pass

    
class Node:
    """
    A part of the tree. It is used to structure the model.
    """
    def __init__(self, question, true_branch, false_branch):
        self.question = question
        self.true_branch = true_branch
        self.false_branch = false_branch
    
    
class DecisionTreeClassifier:
    """
    Decision tree classifier based on CART algorithm.
    """
        
    def __init__(self, metric="gini"):
        self.metric_type = metric
        
    def fit(self, X, y):
        """
        Build the tree, in other words, train the model, and pass it to the class variable.
        Recursion should be used with multiple returns. Return should be either a leaf or a node.
        """
        pass
        
    def predict(self, X):
        """
        Use the model to predict the result with the new data X.
        """
        pass
        
    def print_tree(self):
        """
        It is a helper method to visualize the tree if the model is small. 
        """
        
    @staticmethod
    def _split(X, y, question):
        """
        A private static helper function used to split the node into two nodes based on a question.
        It is a static method because it does not need  the access to class variables.
        But for the completeness of the algorithm, it would be better to still put it inside the class.
            
        Returns:
            true_branch: np array
            false_branch: np array
        """
        pass
            
    def _get_metric(self, y):
        """
        Return:
            gini or entropy: float
                a metric used in the information gain.
        """
            
        if self.metric_type == 'gini':
            pass
        if self.metric_type == 'entropy':
            pass
        
    def _get_info_gain(self, y, true_branch, false_branch):
        """
        Calculate the info gain after a node is splitted into two more nodes.
        """
        if self.metric_type == 'gini':
            pass
        if self.metric_type == 'entropy':
            pass
        
        
    def _find_best_split(self, X, y):
        """
        Return:
            best_question: an instance of Question that get the highest info gain. We use it to split the tree.
            best_gain: the info gain when the best question is asked.
        """
        pass

## Work on individual pieces.

Now we have the basic structure of the code, and most importantly, the big picture of how to build the decision tree, now it's time to work on small pieces.

### First, make a test dataset for code testing.

The dataset looks like this:

```
training_data = [
    ['Green', 3, 'Apple'],
    ['Yellow', 3, 'Apple'],
    ['Red', 1, 'Grape'],
    ['Red', 1, 'Grape'],
    ['Yellow', 3, 'Lemon'],
]
```


The first feature is color, and the second is radius.
The third column is label.

However, since we are going to work with numpy array, it would be better to convert the categorical feature into nominal numbers.

**For the color feature,**

* 1 --> 'green'
* 2 --> 'yellow'
* 3 --> 'red'
   
**For the label,**

* 1 --> 'apple'
* 2 --> 'grape'
* 3 --> 'lemon'

In [3]:
training_data = np.array([
    [1, 3, 1],
    [2, 3, 1],
    [3, 1, 2],
    [3, 1, 2],
    [2, 3, 3],
])

X = training_data[:, :-1]
y = training_data[:, -1]

# A list or numpy array does not have a header, 
# so for demonstration purpose, I manually added a header.
header = ["color", "diameter", "label"]

In [4]:
X

array([[1, 3],
       [2, 3],
       [3, 1],
       [3, 1],
       [2, 3]])

In [5]:
y

array([1, 1, 2, 2, 3])

### Make a Question class. 

In [6]:
class Question:
    """
    A node is splitted based on the question asked.
    """
    def __init__(self, column_number, threshold):
        self.column_number = column_number
        self.threshold = threshold
    
    def __str__(self):
        return "Is {} > {}".format(
            header[self.column_number], self.threshold
        )
    
    def ask(self, x):
        feature = x[self.column_number]
        return feature > self.threshold

In [7]:
# Test if it works

sample_1 = training_data[1, :]
sample_2 = training_data[2, :]
q = Question(1, 1)
print('The question is: ', q)
print('For the first test sample, the answer is: ', q.ask(sample_1))
print('For the second test sample, the answer is: ', q.ask(sample_2))

The question is:  Is diameter > 1
For the first test sample, the answer is:  True
For the second test sample, the answer is:  False


### Make a Leaf class.

In [8]:
class Leaf:
    """
    The end node (where no more info is gained). It should contain the predictions we want with only one type of label.
    """
    def __init__(self, y):
        self.prediction = self._label_counts(y)
        
    
    def __str__(self):
        return str(self.prediction)
    
    @staticmethod
    def _label_counts(y):
        """
        Counts the number of the samples that have the same label.
        Return:
            counts: dict
        """
        
        unique, counts = np.unique(y, return_counts=True)
        
        return dict(zip(unique, counts))

In [9]:
# Test if it works

labels = np.array([3, 3, 1, 2, 1, 3])
leaf = Leaf(labels)
print('This leaf contains the following prediction: ', leaf)

This leaf contains the following prediction:  {1: 2, 2: 1, 3: 3}


### Make a Node class.

**Actually it is so simple that the class has already be completed during the structuring process.**

A little bit more explanation:
1. We need the question in the Node, because the question is more like a guide, pointing where the data should flow. (think about tensorflow).

2. Every node has a true branch, and a false branch. Again, whether data flows into a true branch or a false branch all depends on the question.

In [10]:
class Node:
    """
    A part of the tree. It is used to structure the model.
    """
    def __init__(self, 
                 question, 
                 X_true_branch,
                 y_true_branch,
                 X_false_branch,
                 y_false_branch):
        self.question = question
        self.X_true_branch = X_true_branch
        self.y_true_branch = y_true_branch
        self.X_false_branch = X_false_branch
        self.y_false_branch = y_false_branch

### Now comes the hardest part, let's build the classifier:
Because it is a big class, you should build it step by step, following the order that we have come up with when we were structuring the code.

1. Split data
3. metric
4. info_gain 
5. get_best_split

All the functions above will be part of the model training process, which is the `fit` method in the class.

Then, you can work on the following two methods:

1. predict --> a way to predict new instance based on the trained model.
2. visualization --> a way to visualize the decision tree.

**Remember, after you finish each method, you should test it to make sure it actually works.**

In [11]:
class DecisionTreeClassifier:
    """
    Decision tree classifier based on CART algorithm.
    """
        
    def __init__(self, metric="gini"):
        # hyperparameter
        self.metric_type = metric
        
    def fit(self, X, y):
        """
        Build the tree, in other words, train the model, and pass it to the class variable.
        Recursion should be used with multiple returns. Return should be either a leaf or a node.
        """
        gain, question = self._find_best_split(X, y)
        
        if gain == 0:
            return Leaf(y)
        
        X_true_branch, y_true_branch, X_false_branch, y_false_branch = self._split(X, y, question)
        
        true_node = self.fit(X_true_branch, y_true_branch)
        false_node = self.fit(X_false_branch, y_false_branch)
        
        return Node(question, X_true_branch, y_true_branch, X_false_branch, y_false_branch)
        
        
    def predict(self, X):
        """
        Use the model to predict the result with the new data X.
        """
        pass
    
    @staticmethod
    def print_tree(node, spacing=''):
        """
        It is a helper method to visualize the tree if the model is small. 
        """
        if isinstance(node, Leaf):
            print (spacing + "Predict", node.predictions)
            return

        # Print the question at this node
        print (spacing + str(node.question))

        # Call this function recursively on the true branch
        print (spacing + '--> True:')
        self.print_tree(node.true_branch, spacing + "  ")

        # Call this function recursively on the false branch
        print (spacing + '--> False:')
        self.print_tree(node.false_branch, spacing + "  ")
        
        
    @staticmethod
    def _split(X, y, question):
        """
        A private static helper function used to split the node into two nodes based on a question.
        It is a static method because it does not need  the access to class variables.
        But for the completeness of the algorithm, it would be better to still put it inside the class.
            
        Returns:
            true_branch: np array
            false_branch: np array
        """
        data = np.hstack((X, y.reshape(-1, 1)))
        true_branch = np.array([])
        false_branch = np.array([])
        for row in data:
            if question.ask(row):
                true_branch = np.vstack((true_branch, row)) if true_branch.size else row
            else:
                false_branch = np.vstack((false_branch, row)) if false_branch.size else row
        
        X_true_branch = true_branch[:, :-1]
        y_true_branch = true_branch[:, -1]
        X_false_branch = false_branch[:, :-1]
        y_false_branch = false_branch[:, -1]
        
        return X_true_branch, y_true_branch, X_false_branch, y_false_branch
            
    def _get_metric(self, y):
        """
        Return:
            gini or entropy: float
                a metric used in the information gain.
        """
        n_samples = len(y)
        _, counts = np.unique(y, return_counts=True)
        
        if self.metric_type == 'gini':
            impurity = 1
            for count in counts:
                probability = float(count / n_samples)
                impurity -= probability ** 2
            return impurity
                
        if self.metric_type == 'entropy':
            entropy = 0
            for count in counts:
                probability = float(count / n_samples)
                entropy -= probability * np.log2(probability)
            return entropy
            
        
    def _get_info_gain(self, y, y_true_branch, y_false_branch):
        """
        Calculate the info gain after a node is splitted into two more nodes.
        """
        p_true = len(y_true_branch) / len(y)
        p_false = 1 - p_true
        
        metric_before_split = self._get_metric(y)
        metric_true = self._get_metric(y_true_branch)
        metric_false = self._get_metric(y_false_branch)
        
        gain = metric_before_split - p_true * metric_true - p_false * metric_false
        
        return gain
        
        
    def _find_best_split(self, X, y):
        """
        Return:
            best_question: an instance of Question that get the highest info gain. 
                We use it to split the tree.
            best_gain: the info gain when the best question is asked.
        """
        best_gain = 0
        best_question = None
        n_features = len(X[0])
        
        for column_number in range(n_features):
            thresholds = set([x[column_number] for x in X])
            
            for threshold in thresholds:
                question = Question(column_number, threshold)
                
                # TODO: I need to fix this part
                try:
                    _, y_true_branch, _, y_false_branch = self._split(X, y, question)
                
                except IndexError:
                    continue
                
                gain = self._get_info_gain(y, y_true_branch, y_false_branch)
                
                if gain >= best_gain:
                    best_gain = gain
                    best_question = question
        
        return best_gain, best_question

### Test each method in DecisionTreeClassifier class

#### 1. Test `_split` method:

In [12]:
decision = DecisionTreeClassifier(metric='gini')

a, b, c, d = decision._split(X, y, q) # q is the Question instance previously.
print('X_true_branch is {} \n{}'.format(type(a), a))
print('-------------------------')
print('y_true_branch is {} \n{}'.format(type(b), b))
print('-------------------------')
print('X_false_branch is {} \n{}'.format(type(c), c))
print('-------------------------')
print('y_false_branch is {} \n{}'.format(type(d), d))

X_true_branch is <class 'numpy.ndarray'> 
[[1 3]
 [2 3]
 [2 3]]
-------------------------
y_true_branch is <class 'numpy.ndarray'> 
[1 1 3]
-------------------------
X_false_branch is <class 'numpy.ndarray'> 
[[3 1]
 [3 1]]
-------------------------
y_false_branch is <class 'numpy.ndarray'> 
[2 2]


#### 2. Test `_get_metric` method:
$$
impurity = 1 - \sum_{i=1}^{n} p_i^2
$$

In [13]:
decision = DecisionTreeClassifier(metric='gini')

impurity_1 = decision._get_metric(np.array([1, 1, 1, 1, 1]))
impurity_2 = decision._get_metric(np.array([1, 1, 2, 2]))
impurity_3 = decision._get_metric(np.array([1, 1, 0, 0, 0]))
print('The tested impurities are \n{}\n{}\n{}'.format(
    impurity_1, impurity_2, impurity_3))

The tested impurities are 
0.0
0.5
0.48


$$
entropy = - \sum_{i=1}^{n} p_i {\log_2 p_i}
$$

In [14]:
decision = DecisionTreeClassifier(metric='entropy')

impurity_1 = decision._get_metric(np.array([1, 1, 1, 1, 1]))
impurity_2 = decision._get_metric(np.array([1, 1, 2, 2]))
impurity_3 = decision._get_metric(np.array([1, 1, 0, 0, 0]))
print('The tested impurities are \n{}\n{}\n{}'.format(
    impurity_1, impurity_2, impurity_3))

The tested impurities are 
0.0
1.0
0.9709505944546686


#### 3. Test `_get_info_gain` method:
$$
gain = metric_a - \sum_{i=1}^{n} p_i * metric_b
$$

In [15]:
decision = DecisionTreeClassifier(metric='gini')

_, y_true_branch, _, y_false_branch = decision._split(X, y, q)

gain = decision._get_info_gain(
    y, y_true_branch, y_false_branch
)
print('The info gain is {}'.format(gain))

The info gain is 0.37333333333333324


**4. Test `_find_best_split` method:**

In [16]:
decision = DecisionTreeClassifier(metric='gini')

best_gain, best_question = decision._find_best_split(X, y)
print(best_gain)
print(best_question)

0.37333333333333324
Is diameter > 1


**5. Test `fit` method:**

In [17]:
decision = DecisionTreeClassifier(metric='gini')

tree = decision.fit(X, y)
decision.print_tree(tree)

Is diameter > 1
--> True:


NameError: name 'self' is not defined