## 1. 目标是什么？ 
* 最终目标是建立一个决策树的classifier， 所使用的算法是 **Classification and Regression Tree (CART)**.


* 目标细分为：

    1. 将classifier 作的尽量普遍化， 可以适合各种数据处理，不仅仅是书上的例子。
    2. 将classifier 封装在一个class 里面， 最主要的method 包括训练（fit）， 预测（predict）。

## 2. 前提是什么？
1. 需要真正了解什么是决策树


2. ID3, C4.5， CART 的不同之处

    * CART 是最普遍使用的， 可以用来作regression 和 classification。 二叉树
    * ID3  已经过时， 只能作classification. 多叉数
    * C4.5 ID3 的升级版， 可以作classification 和 regression。 
 
 
3. 建立决策树时所使用的衡量单位（gini impurity, entropy). 

    * ID3 C4.5 ----> entropy
    * CART ------> gini impurity
    * 这个并不是绝对的， 所以我们将把两种metric 都包括在class 里面， 把metric 的选择作为一个hyperparameter
    
    
4. 树结构需要使用编程中递归的概念， 所以需要了解一些递归的知识。


## 3. 如何创建一个class （我个人的理解）：
无论是什么样子的class， 无非就包括两个东西：

1. variable 变量
2. method (or function） 函数

我们可以把变量想象成名词， 函数想象成动词。 比如我们有一个class 叫做 Car。 那么 车的名字， 型号 就是他的变量， 发动， 停止就是函数。 


## 4. 那么创建这个决策树的class， 我们具体都需要什么：
1. 起初， 这个世界没有数。 只有一堆数据。 这堆数据可以看成是节点（node).
1. 向数据提出一个问题。
2. 根据问题的结果（是或者不是）， 从而将数据一分为二。 --> 从一个node 变成了两个 node。
3. 使用info_gain  来判断此分类是否有效。 而info_gain 是通过分前的节点（node）和分后的两个节点（node） 的impurity 或者 entropy的相差而得来的。
4. 经过多次验证， 我们终于得到了最好的info_gain, 同时也知道了什么问题在这个时候该问， 什么时候不该问。
5. 最终， 分裂后的节点里面只包括一种类别， 这个节点就不能再分裂了， 我们叫这个节点 leaf（叶子). 
6. 所以叶子就是不能再分裂了， 而node 还可以继续分裂。 一定要知道他们的不同之处。 leaf 和 node 共同组成了 decision tree。 Leaf 所包含的信息就是我们所需要的prediction。 

![Decision_Tree](img/decision_tree.png)


## 5. 把第4步中我们所考虑到的所有东西， 按照名词和动词来分类：
* 变量 (名词）：
    1. Node （节点）
    2. Leaf （叶子）
    3. Question （问题）
    
* 函数 (动词）：
    1. split (分裂节点）
    2. ask question （问问题来判断）
    3. get_metric (计算 impurity 或者 entropy）
    4. get_info_gain (计算 info_gain)
    5. get_best_split (获得最好的分裂）

## 6. 一些注意事项：

1. 既然是用python来写， 尽量遵循PEP8
2. 命名要简单， 明了。 
3. 尽量写出动态的程序， 不要hardcode （以上三点， 实战的书绝对是一个极端反面教材）。
3. （best practices if you are intermediate in Python）先按照上面的分析， 把整个class 的框架写出来， 然后写测试程序， 最后再写class。 通过写测试， 会让你的整个code 的结构印象更加深刻， 同时后写class 过程中的 debug 提供特别多的帮助。
4. 在写整个框架的时候， 需要把docstring 也写上去， 方便你对整个code 的把控。
5. 除了docstring， 普通的comment不要太多。 要用code 本身去述说， 而不是你的comment。
6. 对重要的一些函数里的变量要提出硬性的规定， 比如在训练模型的时候， 输入的数据必须是numpy array， 或者必须是list， 这样你初期就不需要为这些数据结构的转换而分心。
7. 命名的时候， 要前后一致。 比如我的命名方法是： X 表示的是feature矩阵， x 表示的是feature向量， y 表示 lable 向量。 也就是说，大写字母表示矩阵， 小写字母表示向量。 X 表示 feature， y 表示 label。
8. 抽象原则（The principle of Abstraction)， 参考https://www.jianshu.com/p/683ae1bc87f0

## 7. 以下是我按照写的决策树的class的整体结构。 希望对你有帮助。 
你也可以按照上述的思路，写出一个不同的大体结构， 这都无所谓。并且这个初期结构也并不一定是最终的class的样子。写程序是一个边写，边测试，便改正的过程。 但是初期的整体结构绝对对你的思路和code的把握至关重要。千万不要一言不和， 就不经过思考， 直接写code。磨刀不误砍柴工。

我也写了一个简单的decision tree classifier的最终版本。 你们也可以当作参考。 
https://github.com/superyang713/MachineLearningInAction-Camp/blob/master/Week2/lib/tree.py

下面是使用我写的DecisionTreeClassifier 的例子。同时你也可以看到决策树和knn之间的不同之处。

In [1]:
import numpy as np

In [2]:
class Question:
    """
    A node is splitted based on the question asked.
    """
    def __init__(self, column_number, feature):
        self.column_number = column_number
        self.feature = feature
    
    def __str__(self):
        """
        Some way to represent a question.
        """
        pass
    
    def ask(self, row):
        """
        Return:
            bool
        """  
        pass
    
    
class Leaf:
    """
    The end node (where no more info is gained). It should contain the predictions we want with only one type of label.
    """
    def __init__(self, y):
        self.prediction = self.y[0]
        
    def __str__(self):
        """
        Some way to represent a leaf.
        """
        pass
    
    @staticmethod
    def _label_counts(y):
        """
        Counts the number of the samples that have the same label.
        Return:
            counts: dict
        """
        pass

    
class Node:
    """
    A part of the tree. It is used to structure the model.
    """
    def __init__(self, question, true_branch, false_branch):
        self.question = question
        self.true_branch = true_branch
        self.false_branch = false_branch
    
    
class DecisionTreeClassifier:
    """
    Decision tree classifier based on CART algorithm.
    """
        
    def __init__(self, metric="gini"):
        self.metric_type = metric
        
    def fit(self, X, y):
        """
        Build the tree, in other words, train the model, and pass it to the class variable.
        Recursion should be used with multiple returns. Return should be either a leaf or a node.
        """
        pass
        
    def predict(self, X):
        """
        Use the model to predict the result with the new data X.
        """
        pass
        
    def print_tree(self):
        """
        It is a helper method to visualize the tree if the model is small. 
        """
        
    @staticmethod
    def _split(X, y, question):
        """
        A private static helper function used to split the node into two nodes based on a question.
        It is a static method because it does not need  the access to class variables.
        But for the completeness of the algorithm, it would be better to still put it inside the class.
            
        Returns:
            true_branch: np array
            false_branch: np array
        """
        pass
            
    def _get_metric(self, y):
        """
        Return:
            gini or entropy: float
                a metric used in the information gain.
        """
            
        if self.metric_type == 'gini':
            pass
        if self.metric_type == 'entropy':
            pass
        
    def _get_info_gain(self, y, true_branch, false_branch):
        """
        Calculate the info gain after a node is splitted into two more nodes.
        """
        if self.metric_type == 'gini':
            pass
        if self.metric_type == 'entropy':
            pass
        
        
    def _find_best_split(self, X, y):
        """
        Return:
            best_question: an instance of Question that get the highest info gain. We use it to split the tree.
            best_gain: the info gain when the best question is asked.
        """
        pass

## Work on individual pieces.

Now we have the basic structure of the code, and most importantly, the big picture of how to build the decision tree, now it's time to work on small pieces.

### First, make a test dataset for code testing.

The dataset looks like this:

```
training_data = [
    ['Green', 3, 'Apple'],
    ['Yellow', 3, 'Apple'],
    ['Red', 1, 'Grape'],
    ['Red', 1, 'Grape'],
    ['Yellow', 3, 'Lemon'],
]
```


The first feature is color, and the second is radius.
The third column is label.

However, since we are going to work with numpy array, it would be better to convert the categorical feature into nominal numbers.

**For the color feature,**

* 1 --> 'green'
* 2 --> 'yellow'
* 3 --> 'red'
   
**For the label,**

* 1 --> 'apple'
* 2 --> 'grape'
* 3 --> 'lemon'

In [3]:
training_data = np.array([
    [1, 3, 1],
    [2, 3, 1],
    [3, 1, 2],
    [3, 1, 2],
    [2, 3, 3],
])

X = training_data[:, :-1]
y = training_data[:, -1]

# A list or numpy array does not have a header, 
# so for demonstration purpose, I manually added a header.
header = ["color", "diameter", "label"]

In [4]:
X

array([[1, 3],
       [2, 3],
       [3, 1],
       [3, 1],
       [2, 3]])

In [5]:
y

array([1, 1, 2, 2, 3])

### Make a Question class. 

In [6]:
class Question:
    """
    A node is splitted based on the question asked.
    """
    def __init__(self, column_number, threshold):
        self.column_number = column_number
        self.threshold = threshold
    
    def __str__(self):
        return "Is {} > {}".format(
            header[self.column_number], self.threshold
        )
    
    def ask(self, x):
        feature = x[self.column_number]
        return feature > self.threshold

In [7]:
# Test if it works

sample_1 = training_data[1, :]
sample_2 = training_data[2, :]
q = Question(1, 1)
print('The question is: ', q)
print('For the first test sample, the answer is: ', q.ask(sample_1))
print('For the second test sample, the answer is: ', q.ask(sample_2))

The question is:  Is diameter > 1
For the first test sample, the answer is:  True
For the second test sample, the answer is:  False


### Make a Leaf class.

In [8]:
class Leaf:
    """
    The end node (where no more info is gained). It should contain the predictions we want with only one type of label.
    """
    def __init__(self, y):
        self.prediction = self._label_counts(y)
        
    
    def __str__(self):
        return str(self.prediction)
    
    @staticmethod
    def _label_counts(y):
        """
        Counts the number of the samples that have the same label.
        Return:
            counts: dict
        """
        
        unique, counts = np.unique(y, return_counts=True)
        return unique[np.argmax(counts)]

In [9]:
# Test if it works

labels = np.array([3, 3, 1, 2, 1, 3])
leaf = Leaf(labels)
print('This leaf contains the following prediction: ', leaf)

This leaf contains the following prediction:  3


### Make a Node class.

**Actually it is so simple that the class has already be completed during the structuring process.**

A little bit more explanation:
1. We need the question in the Node, because the question is more like a guide, pointing where the data should flow. (think about tensorflow).

2. Every node has a true branch, and a false branch. Again, whether data flows into a true branch or a false branch all depends on the question.

In [10]:
class Node:
    """
    A part of the tree. It is used to structure the model.
    """
    def __init__(self, question, true_node, false_node):
        self.question = question
        self.true_node = true_node
        self.false_node = false_node

### Now comes the hardest part, let's build the classifier:
Because it is a big class, you should build it step by step, following the order that we have come up with when we were structuring the code.

1. Split data
3. metric
4. info_gain 
5. get_best_split

All the functions above will be part of the model training process, which is the `fit` method in the class.

Then, you can work on the following two methods:

1. visualization --> a way to visualize the decision tree, and test the trained model.
2. predict --> a way to predict new instance based on the trained model.


**Remember, after you finish each method, you should test it to make sure it actually works.**

In [11]:
class DecisionTreeClassifier:
    """
    Decision tree classifier based on CART algorithm.
    """
        
    def __init__(self, metric="gini"):
        # hyperparameter
        self.metric_type = metric
        
    def fit(self, X, y):
        """
        Build the tree, in other words, train the model, and pass it to the class variable.
        Recursion should be used with multiple returns. Return should be either a leaf or a node.
        """
        gain, question = self._find_best_split(X, y)
        
        if gain == 0:
            return Leaf(y)
        
        X_true_branch, y_true_branch, X_false_branch, y_false_branch = self._split(X, y, question)
        
        true_node = self.fit(X_true_branch, y_true_branch)
        false_node = self.fit(X_false_branch, y_false_branch)
        self.tree = Node(question, true_node, false_node)
        return self.tree
    
    def predict(self, X):
        """
        Use the model to predict the result with the new data X.
        """
        n_samples = len(X)                                                                                                                                                         
        y_predict = np.empty(n_samples)                                                                                                                                            
                                                                                                                                                                                   
        for i, x in enumerate(X):                                                                                                                                                  
            y_predict[i] = self._predict(self.tree, x)                                                                                                                             
                                                                                                                                                                                   
        return y_predict      
        
    def _predict(self, tree, x):
        """
        Use the model to predict the result with the new data X.
        """

        if isinstance(tree, Leaf):
            return tree.prediction

        if tree.question.ask(x):
            return self._predict(tree.true_node, x)
        else:
            return self._predict(tree.false_node, x)
          
    def print_tree(self, spacing=''):
        self._print_tree(self.tree, spacing=spacing)
            
            
    def _print_tree(self, tree, spacing=''):
        """
        It is a helper method to visualize the tree if the model is small. Used to test model. 
        """
        if isinstance(tree, Leaf):
            print(spacing + "Predict", tree.prediction)
            return

        # Print the question at this node
        print(spacing + str(tree.question))

        # Call this function recursively on the true branch
        print(spacing + '--> True:')
        self._print_tree(tree.true_node, spacing + "  ")

        # Call this function recursively on the false branch
        print(spacing + '--> False:')
        self._print_tree(tree.false_node, spacing + "  ")
        
        
    @staticmethod
    def _split(X, y, question):
        """
        A private static helper function used to split the node into two nodes based on a question.
        It is a static method because it does not need  the access to class variables.
        But for the completeness of the algorithm, it would be better to still put it inside the class.
            
        Returns:
            true_branch: np array
            false_branch: np array
        """
        data = np.hstack((X, y.reshape(-1, 1)))
        true_branch = np.array([])
        false_branch = np.array([])
        for row in data:
            if question.ask(row):
                true_branch = np.vstack((true_branch, row)) if true_branch.size else row.reshape(1, -1)
            else:
                false_branch = np.vstack((false_branch, row)) if false_branch.size else row.reshape(1, -1)
        
        if len(true_branch) == 0 or len(false_branch) == 0:
            X_true_branch, y_true_branch, X_false_branch, y_false_branch = [], [], [], []
        else:
            X_true_branch = true_branch[:, :-1]
            y_true_branch = true_branch[:, -1]
            X_false_branch = false_branch[:, :-1]
            y_false_branch = false_branch[:, -1]
        
        return X_true_branch, y_true_branch, X_false_branch, y_false_branch
            
    def _get_metric(self, y):
        """
        Return:
            gini or entropy: float
                a metric used in the information gain.
        """
        n_samples = len(y)
        _, counts = np.unique(y, return_counts=True)
        
        if self.metric_type == 'gini':
            impurity = 1
            for count in counts:
                probability = float(count / n_samples)
                impurity -= probability ** 2
            return impurity
                
        if self.metric_type == 'entropy':
            entropy = 0
            for count in counts:
                probability = float(count / n_samples)
                entropy -= probability * np.log2(probability)
            return entropy
            
        
    def _get_info_gain(self, y, y_true_branch, y_false_branch):
        """
        Calculate the info gain after a node is splitted into two more nodes.
        """
        p_true = len(y_true_branch) / len(y)
        p_false = 1 - p_true
        
        metric_before_split = self._get_metric(y)
        metric_true = self._get_metric(y_true_branch)
        metric_false = self._get_metric(y_false_branch)
        
        gain = metric_before_split - p_true * metric_true - p_false * metric_false
        
        return gain
        
        
    def _find_best_split(self, X, y):
        """
        Return:
            best_question: an instance of Question that get the highest info gain. 
                We use it to split the tree.
            best_gain: the info gain when the best question is asked.
        """
        best_gain = 0
        best_question = None
        n_features = len(X[0])
        
        for column_number in range(n_features):
            thresholds = set([x[column_number] for x in X])
            
            for threshold in thresholds:
                question = Question(column_number, threshold)         
                
                X_true_branch, y_true_branch, X_false_branch, y_false_branch = self._split(X, y, question)
                
                if len(X_true_branch) == 0 or len(X_false_branch) == 0:
                    continue
                
                gain = self._get_info_gain(y, y_true_branch, y_false_branch)
                
                if gain >= best_gain:
                    best_gain = gain
                    best_question = question
        
        return best_gain, best_question

### Test each method in DecisionTreeClassifier class

#### 1. Test `_split` method:

In [12]:
decision = DecisionTreeClassifier(metric='gini')

question = Question(1, 1)
X_true_branch, y_true_branch, X_false_branch, y_false_branch = decision._split(X, y, question)
print('X_true_branch is {} \n{}'.format(type(X_true_branch), X_true_branch))
print('-------------------------')
print('y_true_branch is {} \n{}'.format(type(y_true_branch), y_true_branch))
print('-------------------------')
print('X_false_branch is {} \n{}'.format(type(X_false_branch), X_false_branch))
print('-------------------------')
print('y_false_branch is {} \n{}'.format(type(y_false_branch), y_false_branch))

X_true_branch is <class 'numpy.ndarray'> 
[[1 3]
 [2 3]
 [2 3]]
-------------------------
y_true_branch is <class 'numpy.ndarray'> 
[1 1 3]
-------------------------
X_false_branch is <class 'numpy.ndarray'> 
[[3 1]
 [3 1]]
-------------------------
y_false_branch is <class 'numpy.ndarray'> 
[2 2]


#### 2. Test `_get_metric` method:
$$
impurity = 1 - \sum_{i=1}^{n} p_i^2
$$

In [13]:
decision = DecisionTreeClassifier(metric='gini')

impurity_1 = decision._get_metric(np.array([1, 1, 1, 1, 1]))
impurity_2 = decision._get_metric(np.array([1, 1, 2, 2]))
impurity_3 = decision._get_metric(np.array([1, 1, 0, 0, 0]))
print('The tested impurities are \n{}\n{}\n{}'.format(
    impurity_1, impurity_2, impurity_3))

The tested impurities are 
0.0
0.5
0.48


$$
entropy = - \sum_{i=1}^{n} p_i {\log_2 p_i}
$$

In [14]:
decision = DecisionTreeClassifier(metric='entropy')

impurity_1 = decision._get_metric(np.array([1, 1, 1, 1, 1]))
impurity_2 = decision._get_metric(np.array([1, 1, 2, 2]))
impurity_3 = decision._get_metric(np.array([1, 1, 0, 0, 0]))
print('The tested impurities are \n{}\n{}\n{}'.format(
    impurity_1, impurity_2, impurity_3))

The tested impurities are 
0.0
1.0
0.9709505944546686


#### 3. Test `_get_info_gain` method:
$$
gain = metric_a - \sum_{i=1}^{n} p_i * metric_b
$$

In [15]:
decision = DecisionTreeClassifier(metric='gini')

_, y_true_branch, _, y_false_branch = decision._split(X, y, q)

gain = decision._get_info_gain(y, y_true_branch, y_false_branch)
print('The info gain is {}'.format(gain))

The info gain is 0.37333333333333324


**4. Test `_find_best_split` method:**

In [16]:
decision = DecisionTreeClassifier(metric='gini')

best_gain, best_question = decision._find_best_split(X, y)
print('For the main node:')
print(best_gain)
print(best_question)
print('-----------------')
print('after the first split')

X_true_branch, y_true_branch, X_false_branch, y_false_branch = decision._split(X, y, question)
best_gain_true_branch, best_question_true_branch = decision._find_best_split(X_true_branch, y_true_branch)
best_gain_false_branch, best_question_false_branch = decision._find_best_split(X_false_branch, y_false_branch)

print('The best gain for the true branch: {}'.format(best_gain_true_branch))
print('The best gain for the false branch: {}'.format(best_gain_false_branch))
print('The best question for the true branch is: {} '.format(best_question_true_branch))
print('The best question for the false branch is: {} '.format(best_question_false_branch))

For the main node:
0.37333333333333324
Is diameter > 1
-----------------
after the first split
The best gain for the true branch: 0.11111111111111116
The best gain for the false branch: 0
The best question for the true branch is: Is color > 1 
The best question for the false branch is: None 


**5. Test `fit` method:**

In [17]:
decision = DecisionTreeClassifier(metric='gini')

decision.fit(X, y)
decision.print_tree()

Is diameter > 1
--> True:
  Is color > 1
  --> True:
    Predict 1
  --> False:
    Predict 1
--> False:
  Predict 2


In [18]:
decision = DecisionTreeClassifier(metric='entropy')

decision.fit(X, y)
decision.print_tree()

Is diameter > 1
--> True:
  Is color > 1
  --> True:
    Predict 1
  --> False:
    Predict 1
--> False:
  Predict 2


In [19]:
decision = DecisionTreeClassifier(metric='gini')

decision.fit(X, y)
y_predict = decision.predict(X)
print(y_predict)

[1. 1. 2. 2. 1.]
